apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-terraform-repository
  namespace: flux-system
spec:
  interval: 1m
  url: "https://github.com/savagame/gitops-terraform-fluxcd-workflow"
  secretRef:
    name: github-repository-secret
  ref:
    branch: main
